import { Language } from "./types";

export const translations = {
  en: {
    dashboard: 'Dashboard',
    customers: 'Customers',
    loans: 'Loan Entries',
    transactions: 'History',
    invoice: 'Invoice',
    settings: 'Settings',
    totalCustomers: 'Customers',
    totalLoaned: 'Total Loaned',
    repaid: 'Repaid',
    outstanding: 'Outstanding',
    recentTx: 'Recent Transactions',
    noTx: 'No history yet',
    settingsOverview: 'Settings Overview',
    interestRate: 'Interest Rate',
    penaltyRate: 'Penalty Rate',
    discount: 'Discount',
    method: 'Method',
    highRisk: 'High Risk Customers',
    remaining: 'remaining',
    addCustomer: '+ Add Customer',
    searchPlaceholder: 'Search name, phone...',
    noCustomers: 'No customers yet',
    loaned: 'Loaned',
    rate: 'Rate',
    newEntry: '+ New Entry',
    noLoans: 'No loan entries yet',
    loan: 'Loan',
    repayment: 'Repayment',
    allTx: 'History List',
    selectCustomer: '-- Select Customer --',
    selectPrompt: 'Select a customer to view invoice',
    downloadInvoice: 'Download Invoice PDF',
    shareInvoice: 'Share Invoice PDF',
    logo: 'Logo',
    uploadLogo: 'Upload Logo',
    qrUpload: 'Upload QR Image',
    paymentInfo: 'Payment Information',
    bank: 'Bank',
    account: 'Account',
    holder: 'Holder',
    interestSettings: 'Interest Settings',
    paymentDetails: 'Payment Details',
    pinLock: 'PIN Lock',
    pinDesc: 'PIN required when editing/deleting loan entries · Default: 123456',
    currentPin: 'Current PIN',
    newPin: 'New PIN (6 digits)',
    confirmPin: 'Confirm PIN',
    updatePin: 'Update PIN',
    saveSettings: 'Save Settings',
    addCustomerTitle: 'Add Customer',
    editCustomerTitle: 'Edit Customer',
    name: 'Name *',
    phone: 'Phone',
    email: 'Email',
    notes: 'Notes',
    cancel: 'Cancel',
    save: 'Save',
    update: 'Update',
    newLoanTitle: 'New Loan Entry',
    editLoanTitle: 'Edit Loan Entry',
    customer: 'Customer *',
    date: 'Date *',
    loanAmount: 'Loan Amount (฿)',
    repaymentAmount: 'Repayment (฿)',
    txType: 'Transaction Type',
    txTypePlaceholder: 'Disbursement / Payment',
    notesPlaceholder: 'Notes',
    pinVerify: 'PIN Verification',
    pinPrompt: 'Enter PIN to confirm action',
    pinWrong: 'Wrong PIN',
    pinUpdated: 'PIN updated ✓',
    pinWrongCurrent: 'Current PIN is incorrect',
    pinFormat: 'PIN must be 6 digits',
    pinMismatch: 'PINs do not match',
    settingsSaved: 'Settings saved ✓',
    customerSaved: 'Customer saved ✓',
    loanSaved: 'Loan entry saved ✓',
    deleted: 'Deleted',
    nameRequired: 'Name is required',
    selectCustomerFirst: 'Please select a customer first',
    enterAmount: 'Please enter an amount',
    invoiceDownloaded: 'Invoice downloaded ✓',
    deleteCustomerConfirm: 'Delete this customer? All loan entries will also be deleted.',
    language: 'Language',
    english: 'English',
    myanmar: 'မြန်မာ',
    flatMethod: 'Flat Interest',
    compoundMethod: 'Compound Interest',
    penaltyMethod: 'Penalty-Based',
    customer_label: 'Customer',
    invoiceDate: 'Invoice Date',
    totalDebt: 'Total Debt',
    interest: 'Interest',
    totalInterest: 'Total Interest',
    thankYou: 'Thank you for your business!',
    portfolioHealth: 'Portfolio Health',
    repaymentRate: 'Repayment Rate',
    customersActive: 'Customers Active',
    expireDays: 'Expire Days',
    displayAndBrightness: 'Display & Brightness',
    lightTheme: 'Light Mode',
    darkTheme: 'Dark Mode',
    theme: 'Theme',
    dataManagement: 'Data Management',
    backupData: 'Backup Data Info',
    backupBtn: 'Export Backup File',
    restoreBtn: 'Import Backup File',
    restoreSuccess: 'Data restored successfully ✓',
    restoreError: 'Invalid backup file',
    backupDesc: 'Download all data as a file for safety',
    login: 'Login with Google',
    logout: 'Logout',
    syncing: 'Syncing with Cloud...',
    online: 'Cloud Sync Active',
    offline: 'Offline Mode (Local Storage)',
    loginRequired: 'Please login to sync your data to the cloud.',
    installApp: 'Install as Application (APK)',
    installDesc: 'Add to your Home Screen for full-screen and offline access.',
    androidInstall: 'Android: Open in Chrome, tap ⋮ and select "Install app".',
    iosInstall: 'iPhone: Open in Safari, tap Share and select "Add to Home Screen".',
  },
  my: {
    dashboard: 'ပင်မစာမျက်နှာ',
    customers: 'ဖောက်သည်များ',
    loans: 'ချေးငွေများ',
    transactions: 'မှတ်တမ်း',
    invoice: 'ငွေတောင်းခံလွှာ',
    settings: 'ဆက်တင်',
    totalCustomers: 'ဖောက်သည်',
    totalLoaned: 'ချေးငွေစုစုပေါင်း',
    repaid: 'ပြန်ဆပ်ပြီး',
    outstanding: 'ကျန်ရှိသော',
    recentTx: 'လတ်တလောငွေသွားငွေလာ',
    noTx: 'မှတ်တမ်း မရှိသေးဘူး',
    settingsOverview: 'ဆက်တင်အကျဉ်းချုပ်',
    interestRate: 'အတိုးနှုန်း',
    penaltyRate: 'ဒဏ်ငွေနှုန်း',
    discount: 'လျှော့စျေး',
    method: 'နည်းလမ်း',
    highRisk: 'အန္တရာယ်မြင့် ဖောက်သည်',
    remaining: 'ကျန်ရှိ',
    addCustomer: '+ ဖောက်သည်ထည့်',
    searchPlaceholder: 'အမည်၊ ဖုန်းဖြင့် ရှာပါ...',
    noCustomers: 'ဖောက်သည် မရှိသေးဘူး',
    loaned: 'ချေးငွေ',
    rate: 'ပြန်ဆပ်နှုန်း',
    newEntry: '+ ငွေသွင်းမှတ်တမ်းအသစ်',
    noLoans: 'ငွေသွင်းမှတ်တမ်း မရှိသေးဘူး',
    loan: 'ချေးငွေ',
    repayment: 'ပြန်ဆပ်ငွေ',
    allTx: 'မှတ်တမ်းစာရင်း',
    selectCustomer: '-- ဖောက်သည်ရွေးပါ --',
    selectPrompt: 'ဖောက်သည်ရွေးပြီး invoice ကြည့်ပါ',
    downloadInvoice: 'Invoice PDF ဒေါင်းရန်',
    shareInvoice: 'Invoice PDF မျှဝေရန်',
    logo: 'လိုဂို (Logo)',
    uploadLogo: 'လိုဂို တင်ရန်',
    qrUpload: 'QR ပုံစံတင်ရန်',
    paymentInfo: 'ငွေပေးချေမှု သတင်းအချက်အလက်',
    bank: 'ဘဏ်',
    account: 'အကောင့်နံပါတ်',
    holder: 'အကောင့်ပိုင်ရှင်',
    interestSettings: 'အတိုးဆက်တင်',
    paymentDetails: 'ငွေပေးချေမှု အသေးစိတ်',
    pinLock: 'PIN လော့ခ်',
    pinDesc: 'ချေးငွေ ပြင်/ဖျက်တဲ့အခါ PIN တောင်းမည် · မူလ: 123456',
    currentPin: 'လက်ရှိ PIN',
    newPin: 'PIN အသစ် (ဂဏန်း 6 လုံး)',
    confirmPin: 'PIN အသစ် အတည်ပြုပါ',
    updatePin: 'PIN ပြောင်းရန်',
    saveSettings: 'ဆက်တင်သိမ်းရန်',
    addCustomerTitle: 'ဖောက်သည်ထည့်ရန်',
    editCustomerTitle: 'ဖောက်သည်ပြင်ရန်',
    name: 'အမည် *',
    phone: 'ဖုန်းနံပါတ်',
    email: 'အီးမေးလ်',
    notes: 'မှတ်စု',
    cancel: 'မလုပ်တော့ဘူး',
    save: 'သိမ်းမည်',
    update: 'ပြင်မည်',
    newLoanTitle: 'ငွေသွင်းမှတ်တမ်းအသစ်',
    editLoanTitle: 'ငွေသွင်းမှတ်တမ်းပြင်ရန်',
    customer: 'ဖောက်သည် *',
    date: 'ရက်စွဲ *',
    loanAmount: 'ချေးငွေ (฿)',
    repaymentAmount: 'ပြန်ဆပ်ငွေ (฿)',
    txType: 'ငွေသွင်းအမျိုးအစား',
    txTypePlaceholder: 'ထုတ်ပေး / ပြန်ဆပ်',
    notesPlaceholder: 'မှတ်စု',
    pinVerify: 'PIN အတည်ပြုခြင်း',
    pinPrompt: 'လုပ်ဆောင်ချက် အတည်ပြုရန် PIN ထည့်ပါ',
    pinWrong: 'PIN မမှန်ဘူး',
    pinUpdated: 'PIN ပြောင်းပြီးပြီ ✓',
    pinWrongCurrent: 'လက်ရှိ PIN မမှန်ဘူး',
    pinFormat: 'PIN သည် ဂဏန်း 6 လုံး ဖြစ်ရမည်',
    pinMismatch: 'PIN နှစ်ခု မတူဘူး',
    settingsSaved: 'ဆက်တင်သိမ်းပြီးပြီ ✓',
    customerSaved: 'ဖောက်သည်သိမ်းပြီးပြီ ✓',
    loanSaved: 'ငွေသွင်းမှတ်တမ်း သိမ်းပြီးပြီ ✓',
    deleted: 'ဖျက်ပြီးပြီ',
    nameRequired: 'အမည်ထည့်ပါ',
    selectCustomerFirst: 'ဖောက်သည်အရင်ရွေးပါ',
    enterAmount: 'ငွေပမာဏ ထည့်ပါ',
    invoiceDownloaded: 'Invoice ဒေါင်းပြီးပြီ ✓',
    deleteCustomerConfirm: 'ဤဖောက်သည်ကို ဖျက်မည်လား? ငွေသွင်းမှတ်တမ်းများပါ ဖျက်မည်။',
    language: 'ဘာသာစကား',
    english: 'English',
    myanmar: 'မြန်မာ',
    flatMethod: 'ပုံသေအတိုး',
    compoundMethod: 'အတိုးပေါ်အတိုး',
    penaltyMethod: 'ဒဏ်ငွေနှုန်း',
    customer_label: 'ဖောက်သည်',
    invoiceDate: 'ရက်စွဲ',
    totalDebt: 'စုစုပေါင်းကြွေးမြီ',
    interest: 'အတိုး',
    totalInterest: 'အတိုးစုစုပေါင်း',
    thankYou: 'စီးပွားရေး ပူးပေါင်းဆောင်ရွက်မှုကို ကျေးဇူးတင်ပါသည်!',
    portfolioHealth: 'အခြေအနေ',
    repaymentRate: 'ပြန်ဆပ်နှုန်း',
    customersActive: 'လက်ရှိဖောက်သည်',
    expireDays: 'သက်တမ်းကုန်ရက်',
    displayAndBrightness: 'မျက်နှာပြင်နှင့် အလင်းအမှောင်',
    lightTheme: 'Light Mode',
    darkTheme: 'Dark Mode',
    theme: 'ပုံစံ',
    dataManagement: 'ဒေတာ စီမံခန့်ခွဲမှု',
    backupData: 'ဒေတာ မိတ္တူကူးယူခြင်း',
    backupBtn: 'Backup ဖိုင် သိမ်းဆည်းရန်',
    restoreBtn: 'Backup ဖိုင် ပြန်ထည့်ရန်',
    restoreSuccess: 'ဒေတာများ ပြန်လည် ထည့်သွင်းပြီးပါပြီ ✓',
    restoreError: 'မိတ္တူဖိုင် မမှန်ကန်ပါ',
    backupDesc: 'ဒေတာများ ဆုံးရှုံးမှု မရှိစေရန် ဖိုင်အဖြစ် သိမ်းထားပါ',
    login: 'Google ဖြင့် ဝင်ရောက်ရန်',
    logout: 'အကောင့်မှ ထွက်ရန်',
    syncing: 'Cloud ထဲသို့ သိမ်းဆည်းနေသည်...',
    online: 'Cloud နှင့် ချိတ်ဆက်ထားသည်',
    offline: 'Offline အနေဖြင့် အသုံးပြုနေသည်',
    loginRequired: 'ဒေတာများ Cloud ပေါ်သို့ သိမ်းဆည်းရန် အကောင့်ဝင်ပေးပါ',
    installApp: 'ဖုန်းတွင် Application (အစစ်) အဖြစ် ထည့်သွင်းရန်',
    installDesc: 'Home Screen တွင် ထည့်သွင်းပြီး အင်တာနက်မရှိဘဲ Screen အပြည့် အသုံးပြုပါ။',
    androidInstall: 'Android ဖုန်းအတွက်: Chrome ဖြင့်ဖွင့်ပြီး ⋮ မှတစ်ဆင့် "Install app" ကိုနှိပ်ပါ။',
    iosInstall: 'iPhone အတွက်: Safari ဖြင့်ဖွင့်ပြီး Share မှတစ်ဆင့် "Add to Home Screen" ကိုနှိပ်ပါ။',
  }
};
